### PR TITLE
Improve formatting of documentation, fix #49

### LINKED ISSUE #49: Repeated keywords in the autogenerated documentation
* parselglossy version:  b28084a
* Python version: 3.7.0
* Operating System: Ubuntu-18.10

### What I Did
The following `template.yml`
```
keywords:
  - name: foo
    type: int
    docstring: foo
  - name: bar
    type: int
    docstring: bar
  - name: baz
    type: int
    docstring: baz
```
is documented using the CLI command `parselglossy doc template.yml` to give:
```
**Keywords**
 :foo: foo

  **Type** ``int``

**Keywords**
 :foo: foo

  **Type** ``int``

 :bar: bar

  **Type** ``int``

**Keywords**
 :foo: foo

  **Type** ``int``

 :bar: bar

  **Type** ``int``

 :baz: baz

  **Type** ``int``

```

### PR DESCRIPTION
**Pull request by robertodr**
Documentation looks a bit nicer and fixes the repetitions @stigrj noticed with multiple keywords.

Screenshot from 2019-03-27 12-41-35

### CODE REVIEW

**Comment by stigrj** [comment]
Looks great! One more issue, though:

Long docstrings are linebreaked in the `input.rst` file, which leads to the following message using `rst2html.py input.rst >input.html`
```
input.rst:459: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
```
which also ends up in the produced html. The warning goes away if I manually unbreak these lines.

**Comment by robertodr** [comment]
How long is long? I cannot reproduce this.

**Comment by stigrj** [comment]
Hmm, turns out it line breaks at the same place that I do in the `template.yml` file, like this
```
    keywords:
      - name: numerically_exact
        type: bool
        default: false
        docstring: |
          This will use MPI algorithms that guarantees that the output is
          invariant wrt the number of MPI processes.
```

**Comment by robertodr** [comment]
OK, I see now!

**Comment by robertodr** [comment]
I now replace newline characters in the `docstring` with spaces, so the string is stitched back together. Final formatting could be a bit crappy though, as very long lines will exceed their box... I'd leave format beautification for later though.

**Review by stigrj — APPROVED** [review]

**Pull request merged**
