### PR TITLE
partial implementation of the LSDalton grammar

### PR DESCRIPTION
**Pull request by bast**
- lists are missing
- parsing of .mol files is missing

### CODE REVIEW

**Comment by bast** [comment]
This draft PR is working towards #10. One problem to think about is how to adapt input templates to accommodate mol files.

**Comment by bast** [comment]
Requires rebase after #80.

**Comment by robertodr** [comment]
> This draft PR is working towards #10. One problem to think about is how to adapt input templates to accommodate mol files.

Still haven't come up with a solution for this. From the grammar point of view, I think `pyparsing` allows to do "parse N lines that look like this" (though how to pass N is still a mistery to me) Having "template-template" would also help recovering the tagging feature of Getkw.

**Comment by bast** [comment]
I am continuing working on it. I will document/share once this moves forward.

**Comment by bast** [comment]
Giving up on this. We might return to this but I want to first see interest and buy-in from (LS)Dalton communities before investing a lot of time into this.

**Pull request closed without merging**
