### PR TITLE
Getkw grammar

### PR DESCRIPTION
**Pull request by robertodr**
We finally have the Getkw grammar into parselglossy! This means we can parse inputs of the form:
- keywords only
- flat sections
- nested sections

into a Python dictionary and dump it to JSON. See the tests to see how this works in practice. The grammar is recursive so nesting can, in principle, go as deep as one wants.

The tests should be cover what I'd consider all valid Getkw-like inputs, but I honestly have no idea if I _exhausted all the corner cases_. Maybe testing with [Hypothesis](https://hypothesis.works/) could help?

@stigrj the changes in `license_maintainer.py` might be relevant for MRChem and MRCPP. I should really put this tool into its own repository...

### CODE REVIEW

**Comment by bast** [comment]
Awesome! (branch needs a rebase)

**Comment by robertodr** [comment]
Can we get #16 in first?

**Comment by stigrj** [comment]
I think I accidentally found a corner case when testing on some actual MRChem input. The following input section
```
Molecule {
  charge = 0
  $coords
  H  0.0000  0.0000 -0.7000
  H  0.0000  0.0000  0.7000
  $end
}
```
produces the correct JSON:

```
{
  "Molecule": {
    "charge": 0.0,
    "coords": "H  0.0000  0.0000 -0.7000\nH  0.0000  0.0000  0.7000\n"
  }
}
```
but if I leave out the `charge` keyword the data block is treated as an array:
```
{
  "Molecule": [
    "coords",
    "H  0.0000  0.0000 -0.7000\nH  0.0000  0.0000  0.7000\n"
  ]
}
```
It doesn't matter if `charge` is put above or below the data block, what matters is whether or not the data block is the *only* keyword.

**Comment by robertodr** [comment]
Thanks for testing @stigrj I think the grammar needs a massage. And definitely testing needs rethinking.

**Comment by robertodr** [comment]
There is a little problem with the raw data section, which turned up while solving the issue reported by @stigrj. These two, I would say completely identical input files, serialize to two slightly different JSON.
The following:
```
molecule {
  $coords
  H  0.0000  0.0000 -0.7000
  H  0.0000  0.0000  0.7000
  $end
}
```
serializes as:
```
{'molecule': {'coords': 'H  0.0000  0.0000 -0.7000\n  H  0.0000  0.0000  0.7000\n  '}}
```
Whereas this one:
```
molecule {
$coords
H  0.0000  0.0000 -0.7000
H  0.0000  0.0000  0.7000
$end
}
```
serializes as:
```
{'molecule': {'coords': 'H  0.0000  0.0000 -0.7000\nH  0.0000  0.0000  0.7000\n'}}
```
Note that the only difference is the white space. So it is sensitive to the format of the string, which I think must be the case also for the "old" Getkw parser (@stigrj can you please confirm?)
What should we do? Should we attempt to clean up white spaces? It seems a bit hard to come up with a general logic for it...

**Comment by stigrj** [comment]
Considering that the `$data` block is interpreted as a multi-line string I think it's only natural that the white spaces are there if the line is indented. Actually, I think I was told back in the days by Jonas *not to indent* the data blocks, so I usually write like this
```
Molecule {
  charge = 0
  multiplicity = 1
$coords
H   0.0   0.0   -0.7
H   0.0   0.0    0.7
$end
}
```
One could of course preprocess the file and remove all indentation first (as with the lowercasing), on *all* keywords and sections. Is there a corresponding `$data` block in other possible grammars where indentation matters, like YAML?

**Comment by stigrj** [comment]
It's perhaps a bit strange that the indentation spacing appears at the *end* of each string? Is it possible to define the block as strictly the lines *between* `$coord` and `$end`, and then include *everything* on these lines, from start to `\n`? Then the following
```
Molecule {
  $coords
  H  0.0  0.0 -0.7
  H  0.0  0.0  0.7
  $end
}
```
gives the following JSON
```
{'molecule': {'coords': '  H  0.0  0.0 -0.7\n  H  0.0  0.0  0.7\n'}}
```

**Comment by robertodr** [comment]
After a little more thinking: there will be no problems as long as the consumer of the JSON knows how to chop up the string. The most natural chopping is the newline character `\n`, but that's neither a concern for the grammar nor for the validation: this is specifically an escape valve in this specific grammar for arbitrary pieces of data that can only be checked downstream.

I'd rather not touch the definition of the `data` terminal in the grammar. White space at the very beginning and very end can be stripped with `strip` after parsing, whereas convincing `pyparsing` that certain white spaces need to be treated differently will blow up in my face.

**Comment by stigrj** [comment]
Agreed! I would anyway like to avoid `$data` blocks in the new MRChem input

**Comment by robertodr** [comment]
I'm wondering whether it could be considered a security issue even, as you can inject arbitrary strings into the code...

**Comment by robertodr** [comment]
I don't know how to get Tox to install Hypothesis from `setup.py`...

**Review by bast — APPROVED** [review]

**Pull request merged**
