### PR TITLE
Use Flit for packaging, close #92

### LINKED ISSUE #92: Not sure how to run the script/generator
This is what I tried:
```
$ poetry install -v
$ poetry run parselglossy --help

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parseglossy'
```

Then (not knowing poetry well enough) I created a new folder, new venv and pip installed from the source folder, then:
```
$ parselglossy --help

Traceback (most recent call last):
  File "/home/user/tmp/foo/venv/bin/parselglossy", line 5, in <module>
    from parseglossy.cli import cli
ModuleNotFoundError: No module named 'parseglossy'
```

### PR DESCRIPTION
**Pull request by robertodr**
The GitHub deployment action needs to be done too.

### CODE REVIEW

**Comment by robertodr** [comment]
Now failing horribly because I didn't adjust the testing action :facepalm: But the installation of the script does work now!

**Comment by bast** [comment]
Should I take it from here and adjust that or are you working on it?

**Comment by robertodr** [comment]
Working on it

**Comment by robertodr** [comment]
@bast Ready for review! The deployment was copied from xcauto, but is still untested.

**Comment by bast** [comment]
For the deploy step I think we should use https://github.com/dftlibs/xcauto/blob/master/.github/workflows/package.yml unmodified. It is well tested.

In particular:
- We should use an API token instead of user/password (perhaps this is already the case)
- I don't think we should run the deploy step on all Linux, macOS, and Windows, it will fail on 2 of them. We would need to run it on all if we wanted binary distributions but here it's a source distribution.

We can adjust this later and this does not have to block this PR.

**Comment by bast** [comment]
And since you nicely listed the dev/test dependencies in pyproject.toml, I agree that in this case we probably don't need `requirements.txt` at all then. Possibly only containing `flit` to bootstap a venv.

**Review by bast — APPROVED** [review]

**Comment by robertodr** [comment]
Let's fix the deploy in another step. I'll clean `requirements.txt`. Note that `flit install --symlink` will install all of dev, test, and doc dependencies.

**Comment by bast** [comment]
> Let's fix the deploy in another step. I'll clean `requirements.txt`. Note that `flit install --symlink` will install all of dev, test, and doc dependencies.

yeah this is much nicer than lazy me who threw this into requirements.txt

**Comment by bast** [comment]
Deploy step followed up in #94.

**Pull request merged**
