### PR TITLE
Use Pipfile only to specify test deps, fix #22

### LINKED ISSUE #22: Consolidate specification of dependencies
We have dependencies for development (specified in `Pipfile`), testing (installed with `pip` on CI services, see the YAML files), and deployment (installed with `pip install parselglossy`).
This is problematic as we can easily lose track of dependencies in this way.

### PR DESCRIPTION
**Pull request by robertodr**
As discussed in #22. Time spent on CI nearly _doubles_, but it's a necessary evil, I would say.

### CODE REVIEW

**Review by bast — APPROVED** [review]
Thanks!

**Comment by bast** [comment]
"Waiting for status to be reported" - is this something new?

**Comment by robertodr** [comment]
I removed that integration, but it seems the bot didn't get the memo...

**Comment by robertodr** [comment]
:robot: pacified now.

**Pull request merged**
