### PR TITLE
Empty lists

### PR DESCRIPTION
**Pull request by robertodr**
Thanks to this answer on [StackOverflow](https://stackoverflow.com/a/55208202/2528668) we can now throw a meaningful exception when parsing an empty list. ~I have also switched from YAPF to [Black](https://github.com/ambv/black) as code formatter.~
Please tag a new release after merging this one.

### CODE REVIEW

**Comment by bast** [comment]
Flake8 complains. Should we not wait with releases until the code solidifies a bit more? I would mint the release for the ACS talk but not before. But perhaps it's time for that. Since it is now only "us", nobody else really depends on the versions. Perhaps I am wrong.

**Comment by bast** [comment]
Also in future please separate feature changes from auto-styling - the new features are now a bit hidden among a lot of trivial style changes applied by Black (I guess).

**Comment by robertodr** [comment]
Yes, it's quite messy. Apologies, I'm separating the styling changes, also because Black only works with Py3.6+ and I am not sure how to split up this stuff from actual development dependencies. What a mess.

As for releases and tags, I see no problem in _not_ having them. I forget it's quite easy to install directly from sources.

**Review by bast — APPROVED** [review]
Looks very good - thanks!

**Pull request merged**
