### PR TITLE
document that we support Python 3.6 or later

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Review by robertodr — APPROVED** [review]
I'll merge after removing the use of F-strings so that Py3.4 and Py3.5 tests pass.

**Comment by bast** [comment]
I will rebase this as soon as other PRs are in.

**Comment by robertodr** [comment]
Given the current testing debacle (_j'ai les yeux plus ~grand~ gros que le ventre_) I would state that we only support Py 3.6+ for the moment being, but that we have plans for Py 3.4+ once the dust settles.

**Comment by robertodr** [comment]
Did you rebase? Or should I just merge?

**Comment by bast** [comment]
Oops sorry for not doing what I promised up there - let's just merge :-)

**Pull request merged**
